@startuml
'https://plantuml.com/class-diagram

class app
class empInfo
() exercise32_input.txt
() console

app "return functions" *--> "readData" empInfo
exercise32_input.txt -> app : read File
app -> console : output table


class app {
readData()
outputData()
}

class empInfo {
returnFName()
returnLName()
returnSalary()
}

@enduml