@startuml
'https://plantuml.com/class-diagram

class app
() userInput
() website_folder

userInput -> app : input values
app -> website_folder : create files


class app {
validateInput()
parseInput()
createWebsite()
createIndex()
}

@enduml